services:
  backend:
    build:
      context: ./backend
    container_name: doc_rag_backend
    ports:
      - "8000:8000"
    volumes:
      - ./backend/chroma_db:/app/chroma_db
      - ./backend:/app
    environment:
      - CHROMA_PERSIST_DIRECTORY=/app/chroma_db
      - GOOGLE_API_KEY=${GOOGLE_API_KEY}

  frontend:
    build:
      context: ./frontend
    container_name: doc_rag_frontend
    ports:
      - "8501:8501"
    volumes:
      - ./frontend:/app
    environment:
      - API_URL=http://backend:8000/api
    depends_on:
      - backend
